function drawPoint(p, markerType, markerColor, markerSize)
	hold on; % Замораживаем текущие оси координат
	plot(p.Z, p.R, markerType,...
	'LineWidth',1.0,...
	'MarkerEdgeColor', markerColor, ...
	'MarkerFaceColor', markerColor, ...
	'MarkerSize', markerSize);
	hold off; % Замораживаем текущие оси координат
end

